# Generated by Django 5.0.3 on 2024-04-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startstrona', '0002_stanstrony'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanstrony',
            name='nazwa',
            field=models.CharField(default='DEAFULTNAME', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
