# Generated by Django 5.0.3 on 2024-04-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startstrona', '0003_stanstrony_nazwa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stanstrony',
            name='nazwa',
            field=models.CharField(default='Domyślna nazwa', max_length=100),
        ),
    ]
