# Generated by Django 5.0.3 on 2024-04-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startstrona', '0005_auto_20240408_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanstrony',
            name='h1',
            field=models.CharField(default='Wpisz h1', max_length=200),
        ),
        migrations.AlterField(
            model_name='stanstrony',
            name='nazwa',
            field=models.CharField(default='Domyślna nazwa', max_length=100, unique=True),
        ),
    ]
