# Generated by Django 5.0.3 on 2024-04-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Startstrona', '0007_alter_stanstrony_nazwa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stanstrony',
            name='h1',
        ),
        migrations.AddField(
            model_name='stanstrony',
            name='Naglowek',
            field=models.CharField(default='Wpisz naglowek', max_length=200),
        ),
        migrations.AddField(
            model_name='stanstrony',
            name='Stopka',
            field=models.CharField(default='Wpisz stopke', max_length=200),
        ),
        migrations.AddField(
            model_name='stanstrony',
            name='Tekst_glowny',
            field=models.CharField(default='Wpisz tekst glowny', max_length=200),
        ),
    ]
